// src/lib/products.ts
import type { Product } from '@/types';

export const PRODUCTS: Product[] = [
  {
  id: 0,
  name: 'Oversize SB-01',
  subtitle: 'Chrome Effect',
  price: 85000,
  img: "/images/SvBlack1.png",
  desc: 'Camiseta color Negro de molde Oversize 100% Algodón Pima. Detalle bordado en pecho.',
  category: 'Camisetas',
  sizes: ['S', 'M', 'L', 'XL'],
  },
  {
  id: 1,
  name: 'Oversize White Ross',
  subtitle: 'Genesis Drop Vol.02',
  price: 89000,
  img: "/images/WhRoss.png",
  desc: 'Camiseta color Crema Oversize. Estampado "Genesis" en espalda con detalle en rojo premium.',
  category: 'Camisetas',
  sizes: ['S', 'M', 'L', 'XL'],
  },
  {
  id: 2,
  name: 'Hoodie RBTH',
  subtitle: 'Move With Purpose',
  price: 165000,
  img: "/images/Hoodie-RBTH.png",
  desc: 'Hoodie de molde Oversize elaborado en 100% Algodón Pima. Estampado RBTH en frente y detalle collab. Hecho en Colombia.',
  category: 'Hoodies',
  sizes: ['S', 'M', 'L', 'XL'],
  },
  {
    id: 3,
    name: 'Hoodie Rebirth X Studios',
    subtitle: 'Designer/Brand 2003',
    price: 155000,
    img: "/images/Hoodie-STUDIO.png",
    desc: 'Hoodie color Café de molde Oversize. Estampado Rebirth X Studios Archive en espalda.',
    category: 'Hoodies',
    sizes: ['S', 'M', 'L', 'XL'],
  },
  {
  id: 4,
  name: 'Oversize GB-02',
  subtitle: 'Genesis Drop Vol.01',
  price: 95000,
  img: "/images/GrBlack1.png",
  desc: 'Camiseta color Gris de molde Oversize elaborado en 100% Algodón Pima Peruano de 220 gramos. Una prenda con estampado en semi-alta densidad, vinilos textiles en colores premium y un aplique 3D.',
  category: 'Camisetas',
  sizes: ['S', 'M', 'L', 'XL'],
  },
  {
    id: 5,
    name: 'Oversize CEO',
    subtitle: 'CEO Of My Own Business',
    price: 92000,
    img: "/images/CeoRbth.png",
    desc: 'Camiseta color Gris Oversize con estampado CEO Of My Own Business.',
    category: 'Camisetas',
    sizes: ['S', 'M', 'L', 'XL'],
  },
  {
    id: 6,
    name: 'Call Me',
    subtitle: 'Estoy Soltero',
    price: 75000,
    img: "/images/Soltero311.png",
    desc: 'Hoodie negro con diseño BBTH vertical. Confeccionado en Algodón Pima 100%.',
    category: 'Camisetas',
    sizes: ['S', 'M', 'L', 'XL'],
  },
  {
    id: 7,
    name: 'Oversize Ocean Eyes',
    subtitle: 'Genesis Drop Vol.02',
    price: 79000,
    img: "/images/OceanEyes.png",
    desc: 'Camiseta negra con diseño "Genesis" en azul. Eternal Street · Clothing Wear · Designs Brand.',
    category: 'Camisetas',
    sizes: ['S', 'M', 'L', 'XL'],
  },
];
